version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:17-alpine
    container_name: adquisiciones-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-adquisiciones_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Change_This_Password_123!}
      POSTGRES_DB: ${POSTGRES_DB:-adquisiciones_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations
    networks:
      - adquisiciones-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-adquisiciones_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # .NET 9 Web API Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: adquisiciones-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS:-5000}
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=${POSTGRES_DB:-adquisiciones_db};Username=${POSTGRES_USER:-adquisiciones_user};Password=${POSTGRES_PASSWORD:-Change_This_Password_123!}
      - JWT__Secret=${JWT__Secret:-ThisIsAVeryLongSecretKeyForJWTTokenGeneration_ChangeThis_MinimumLength64Characters!}
      - JWT__Issuer=${JWT__Issuer:-AdquisicionesAPI}
      - JWT__Audience=${JWT__Audience:-AdquisicionesClient}
      - JWT__ExpirationMinutes=${JWT__ExpirationMinutes:-60}
      - CORS__AllowedOrigins=${CORS__AllowedOrigins:-http://localhost:8080}
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - adquisiciones-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Vue.js 3 Frontend with Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:5000}
    container_name: adquisiciones-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - adquisiciones-network

networks:
  adquisiciones-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
